language: node_js
node_js:
  - "4"
  - "4.4"
  - "5"
  - "6"
  - "7"
  - "node"

script:
  - "npm test"

notifications:
  email: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
